package com.contentfoundry.replypilot;

import static org.junit.Assert.*;
import java.net.InetAddress;
import java.util.List;
import org.junit.Test;

public class LinkPreviewPolicyTest {
    private static void blocked(String value){assertThrows(IllegalArgumentException.class,()->LinkPreviewPolicy.previewUrl(value));}
    private static boolean publicIp(String literal)throws Exception{return LinkPreviewPolicy.publicAddress(InetAddress.getByName(literal).getAddress());}

    @Test public void opensExplicitHttpAndPreservesOriginalFragment(){assertEquals("https://example.com/path?q=one#two",LinkPreviewPolicy.openUrl("HTTPS://EXAMPLE.COM:443/path?q=one#two"));assertEquals("http://192.168.1.1:8080/",LinkPreviewPolicy.openUrl("http://192.168.1.1:8080"));}
    @Test public void rejectsNonWebCredentialsAndAmbiguousAuthority(){for(String value:List.of("javascript:alert(1)","file:///x","intent://x","https://name:secret@example.com","https://@example.com","https://name%40x@example.com","https://example.com:","https://example.com:0","https://example.com:65536","https://example.com\\@evil.example.com"))assertThrows(value,IllegalArgumentException.class,()->LinkPreviewPolicy.openUrl(value));}
    @Test public void rejectsLiteralAndEncodedControls(){for(String value:List.of("https://example.com/a\nb","https://example.com/\u202eb","https://example.com/%0d%0aHeader:x","https://example.com/%5cnext","https://example.com/a b"))assertThrows(value,IllegalArgumentException.class,()->LinkPreviewPolicy.openUrl(value));}
    @Test public void previewRequiresPublicHttpsDefaultPort(){for(String value:List.of("http://example.com/","https://example.com:8443/","https://localhost/","https://printer/","https://a.local/","https://a.internal/","https://a.home/","https://a.test/","https://example.com./"))blocked(value);assertEquals("https://example.com/path",LinkPreviewPolicy.previewUrl("https://example.com:443/path"));}
    @Test public void privateLiteralFormsCannotBypassDns(){for(String value:List.of("https://127.0.0.1/","https://127.1/","https://2130706433/","https://[::1]/","https://[::ffff:127.0.0.1]/","https://[64:ff9b::a00:1]/","https://[2002:a00:1::]/","https://[fe80::1%25wlan0]/"))blocked(value);}
    @Test public void ipv4SpecialRangesFailClosed()throws Exception{for(String value:List.of("0.1.2.3","10.8.0.1","100.64.0.1","100.127.255.254","127.5.6.7","169.254.169.254","172.16.0.1","172.31.255.255","192.0.0.9","192.0.2.1","192.168.7.1","192.88.99.1","198.18.0.1","198.19.255.254","198.51.100.1","203.0.113.1","224.0.0.1","255.255.255.255"))assertFalse(value,publicIp(value));}
    @Test public void ordinaryGlobalAddressesRemainAvailable()throws Exception{for(String value:List.of("8.8.8.8","1.1.1.1","100.128.0.1","172.15.0.1","172.32.0.1","2001:4860:4860::8888","2606:4700:4700::1111"))assertTrue(value,publicIp(value));}
    @Test public void ipv6SpecialAndTransitionRangesAreBlocked()throws Exception{for(String value:List.of("::","::1","::ffff:10.0.0.1","64:ff9b::808:808","64:ff9b:1::1","100::1","2001::1","2001:2::1","2001:db8::1","2002:808:808::1","3fff::1","fc00::1","fe80::1","ff02::1"))assertFalse(value,publicIp(value));}
    @Test public void mixedDnsAnswerCannotUsePrivateFallback()throws Exception{InetAddress good=InetAddress.getByAddress(new byte[]{8,8,8,8}),bad=InetAddress.getByAddress(new byte[]{10,0,0,1});assertEquals(List.of(good),LinkPreviewPolicy.publicAddresses(List.of(good)));assertThrows(IllegalArgumentException.class,()->LinkPreviewPolicy.publicAddresses(List.of(good,bad)));assertThrows(IllegalArgumentException.class,()->LinkPreviewPolicy.publicAddresses(List.of()));}
    @Test public void redirectsAndImagesUseSameStrictRules(){assertEquals("https://example.com/image.jpg",LinkPreviewPolicy.resolvePreview("https://example.com/posts/1","../image.jpg"));for(String value:List.of("http://example.com/image.jpg","//127.0.0.1/a","https://user@example.com/a","\\\\example.com/a","data:image/png;base64,AAAA","javascript:alert(1)","https://example.com/%0a"))assertThrows(value,IllegalArgumentException.class,()->LinkPreviewPolicy.resolvePreview("https://example.com/",value));}
    @Test public void extractsCanonicalLinksWithoutSentencePunctuation(){assertEquals(List.of("https://example.com/a_(b)#part","http://example.org/x"),LinkPreviewPolicy.links("See (https://EXAMPLE.com/a_(b)#part), then http://example.org/x. https://example.com/a_(b)#part"));assertTrue(LinkPreviewPolicy.contains("https://EXAMPLE.com:443/a","https://example.com/a"));assertFalse(LinkPreviewPolicy.contains("https://example.com/a","https://example.com/b"));}
    @Test public void extractionIsBoundedAndDoesNotGuess(){assertTrue(LinkPreviewPolicy.links("www.example.com email@example.com").isEmpty());assertEquals(8,LinkPreviewPolicy.links(java.util.stream.IntStream.range(0,20).mapToObj(i->"https://example.com/"+i).reduce("",(a,b)->a+" "+b)).size());assertTrue(LinkPreviewPolicy.links("x".repeat(32768)+" https://example.com/").isEmpty());assertThrows(IllegalArgumentException.class,()->LinkPreviewPolicy.openUrl("https://example.com/"+"a".repeat(2048)));}
    @Test public void formatBoundaryMatchesDisplayExtraction(){assertEquals(List.of("https://example.com/a"),LinkPreviewPolicy.links("https://example.com/a\u202eHidden"));assertEquals(List.of("https://example.com/a%7Bb%7D"),LinkPreviewPolicy.links("https://example.com/a{b}"));}
    @Test public void parsesOpenGraphPrecedenceAndEntities(){var data=LinkPreviewPolicy.metadata("<head><title>Fallback</title><meta name='twitter:title' content='Tweet'><meta property='OG:TITLE' content='Tom &amp; Jerry'><meta property='og:description' content=' A useful   description '><meta property='og:site_name' content='Example'><meta property='og:image:url' content='/photo.jpg'></head>","https://example.com/post");assertTrue(data.available());assertEquals("Tom & Jerry",data.title());assertEquals("A useful description",data.description());assertEquals("Example",data.siteName());assertEquals("https://example.com/photo.jpg",data.image());}
    @Test public void ignoresDocumentBaseWhenResolvingImage(){var data=LinkPreviewPolicy.metadata("<head><base href='https://127.0.0.1/'><meta property='og:title' content='Page'><meta property='og:image' content='photo.jpg'></head>","https://example.com/posts/1");assertEquals("https://example.com/posts/photo.jpg",data.image());}
    @Test public void unsafeImageDoesNotDestroyTextCard(){var data=LinkPreviewPolicy.metadata("<title>Readable article</title><meta property='og:image' content='http://192.168.1.1/x'>","https://example.com/");assertTrue(data.available());assertEquals("",data.image());}
    @Test public void handlesMalformedMarkupAndDoesNotExecuteScripts(){var data=LinkPreviewPolicy.metadata("<TITLE>Some &lt;article&gt;</TITLE><meta name=description content='A description'><script>throw Error('never executed')</script>","https://example.com/");assertTrue(data.available());assertEquals("Some <article>",data.title());assertEquals("A description",data.description());}
    @Test public void loginAndChallengePagesAreUnavailable(){for(String title:List.of("Log in to Facebook","Instagram - Sign In","Just a moment...","Access denied","Checking your browser"))assertFalse(title,LinkPreviewPolicy.metadata("<title>"+title+"</title><meta property='og:image' content='/a.jpg'>","https://example.com/").available());}
    @Test public void metadataLengthsAndInspectionAreBounded(){var data=LinkPreviewPolicy.metadata("<title>"+"x".repeat(1000)+"</title><meta name=description content='"+"z".repeat(1000)+"'>","https://example.com/");assertEquals(160,data.title().length());assertEquals(280,data.description().length());assertFalse(LinkPreviewPolicy.metadata("x".repeat(LinkPreviewPolicy.MAX_HTML+1),"https://example.com/").available());}
    @Test public void plainMetadataIsCleanAndDoesNotSplitSurrogates(){assertEquals("Hello world",LinkPreviewPolicy.clean(" Hello\n world\u202e ",80));assertEquals("a",LinkPreviewPolicy.clean("a😀",2));assertEquals("a😀",LinkPreviewPolicy.clean("a😀",3));}
}
