package com.contentfoundry.replypilot;

import org.junit.Test;
import static org.junit.Assert.*;
import java.nio.charset.StandardCharsets;

public class MmsSendPolicyTest {
    @Test public void requestIdsCannotBecomePaths(){assertTrue(MmsSendPolicy.id("00000000-0000-0000-0000-000000000001"));for(String bad:new String[]{"../other","","00000000-0000-0000-0000-000000000001/extra","00000000-0000-0000-0000-000000000001?other"})assertFalse(MmsSendPolicy.id(bad));assertFalse(MmsSendPolicy.id(null));}
    @Test public void carrierBudgetIsBounded(){assertEquals(300*1024,MmsSendPolicy.carrierBytes(300*1024));assertEquals(MmsSendPolicy.MAX_CARRIER,MmsSendPolicy.carrierBytes(Integer.MAX_VALUE));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.carrierBytes(0));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.carrierBytes(16383));}
    @Test public void emptyCaptionsWorkButOversizeDoesNot(){assertEquals("",MmsSendPolicy.caption(""));assertEquals("a".repeat(1600),MmsSendPolicy.caption("a".repeat(1600)));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.caption("a".repeat(1601)));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.caption(null));}
    @Test public void genericFilesCannotMasqueradeAsImages(){assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.mime("this is not a picture".getBytes(StandardCharsets.UTF_8),"image/jpeg"));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.mime("%PDF-1.7".getBytes(StandardCharsets.UTF_8),"application/pdf"));}
    @Test public void supportedPhotoMagicIsRecognized(){assertEquals("image/jpeg",MmsSendPolicy.mime(new byte[]{(byte)255,(byte)216,(byte)255,0},"application/octet-stream"));assertEquals("image/png",MmsSendPolicy.mime(new byte[]{(byte)137,80,78,71,13,10,26,10},"image/png"));assertEquals("image/gif",MmsSendPolicy.mime("GIF89a...".getBytes(StandardCharsets.US_ASCII),"image/gif"));}
    @Test public void videoAndAudioContainersNeedSupportedTypes(){byte[] mp4={0,0,0,24,102,116,121,112,105,115,111,109};assertEquals("video/mp4",MmsSendPolicy.mime(mp4,"video/mp4"));assertEquals("audio/mp4",MmsSendPolicy.mime(mp4,"audio/mp4"));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.mime(mp4,"application/octet-stream"));assertEquals("audio/amr",MmsSendPolicy.mime("#!AMR\n123".getBytes(StandardCharsets.US_ASCII),"audio/amr"));}
    @Test public void contactCardsMustBeBoundedAndComplete(){assertEquals("text/x-vcard",MmsSendPolicy.mime("BEGIN:VCARD\nVERSION:3.0\nFN:Test\nEND:VCARD".getBytes(StandardCharsets.UTF_8),"text/vcard"));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.mime("BEGIN:VCARD\nFN:Missing end".getBytes(StandardCharsets.UTF_8),"text/vcard"));assertThrows(IllegalArgumentException.class,()->MmsSendPolicy.mime(("BEGIN:VCARD\n"+"a".repeat(65536)+"\nEND:VCARD").getBytes(StandardCharsets.UTF_8),"text/vcard"));}
    @Test public void attachmentNamesDoNotLeakPaths(){assertEquals(".. private photo.jpg",MmsSendPolicy.name("../private/photo.jpg","image/jpeg"));assertEquals(100,MmsSendPolicy.name("x".repeat(110),"image/jpeg").length());assertEquals("Attachment.jpg",MmsSendPolicy.name(null,"image/jpeg"));}
    @Test public void httpSuccessDoesNotProveCarrierAcceptance(){assertEquals("unknown",MmsSendPolicy.outcome(true,"rp1",null,null));assertEquals("unknown",MmsSendPolicy.outcome(true,"rp1","other",128));assertEquals("unknown",MmsSendPolicy.outcome(true,"rp1","rp1",0));}
    @Test public void onlyMatchingAcceptedConfirmationMarksSent(){assertEquals("sent",MmsSendPolicy.outcome(true,"rp1","rp1",128));assertEquals("unknown",MmsSendPolicy.outcome(false,"rp1","rp1",128));}
    @Test public void carrierRejectionNeverLooksSent(){for(int error:new int[]{129,130,135,192,193,195,224,229,235})assertEquals("failed",MmsSendPolicy.outcome(true,"rp1","rp1",error));assertEquals("unknown",MmsSendPolicy.outcome(true,"rp1","rp1",196));assertEquals("unknown",MmsSendPolicy.outcome(true,"rp1","rp1",255));}
    @Test public void terminalCallbacksCannotResendOrOverwrite(){assertTrue(MmsSendPolicy.callbackAllowed("sending"));assertTrue(MmsSendPolicy.callbackAllowed("unknown"));for(String terminal:new String[]{"sent","failed","preparing",""})assertFalse(MmsSendPolicy.callbackAllowed(terminal));assertTrue(MmsSendPolicy.terminal("sent"));assertTrue(MmsSendPolicy.terminal("failed"));assertFalse(MmsSendPolicy.terminal("unknown"));}
}
