const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
const url=process.env.REPLY_PILOT_URL||'http://127.0.0.1:18769';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let phase='setup';try{
 const page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{
  const interval=window.setInterval;window.setInterval=(fn,ms,...args)=>ms===3500?0:interval(fn,ms,...args);
  const clone=value=>JSON.parse(JSON.stringify(value));window.calls=[];window.saveReplies=[];window.holdSave=false;window.failSave=false;
  window.fixture={defaultSms:true,permissions:true,contactsAllowed:true,notifications:true,exact:true,sims:[{id:1,name:'Fictional SIM'}],sub:1,autoDraft:true,matchMyStyle:true,tone:'Natural',delay:300,theme:'midnight',cloud:{configured:true},jobs:[],inbox:[{thread_id:1,name:'Test partner',address:'+12025550101',body:'Fictional message',date:41000,type:1},{thread_id:2,name:'Other person',address:'+12025550102',body:'A different conversation',date:42000,type:1}]};
  window.chats=Object.fromEntries(fixture.inbox.map(row=>[row.thread_id,{base:40+row.thread_id,history:[{_id:40+row.thread_id,type:1,body:row.body,date:row.date}],hasMore:false,draft:{body:'Existing manual draft',engine:'Edited by you',alternatives:'[]'},relationship:{body:'Existing relationship notes',samples:'',cloudEnabled:row.thread_id===1,autoDraft:row.thread_id===1,autoSend:row.thread_id===1,autoDelay:900,autoDelayMode:'fixed',autoDelayMin:300,autoDelayMax:1800,engagement:row.thread_id===1?'always_reply':'natural',shareLocation:false,relationshipKind:'Friend',tone:'Myself (beta)'},replyEligibility:{eligible:true,total:20,owner:10,incoming:10}}]));
  window.Native={call(id,action,raw){const p=JSON.parse(raw);calls.push({action,p});const done=(value,error=null)=>nativeResult(id,clone(value),error);const reply=()=>{
   if(action==='snapshot')done(fixture);else if(action==='conversation')done(chats[p.thread]);
   else if(action==='saveProfile'){if(failSave){done(null,'Profile could not be saved.');return;}chats[p.thread].relationship={...p,insideJokes:p.insideJokes.trim(),revision:(chats[p.thread].relationship.revision||0)+1};done(chats[p.thread].relationship);}
   else done({});
  };if(action==='saveProfile'&&holdSave)saveReplies.push(reply);else setTimeout(reply,0);}};
 });
 const slider=()=>page.locator('#person-humor-level'),notes=()=>page.locator('#person-inside-jokes');
 const setup=()=>page.locator('[data-action=toggle-profile]').click(),close=()=>page.locator('[data-action=close-setup]').click();
 const open=async thread=>{await page.locator(`.row[data-thread="${thread}"]`).click();await page.locator('#draft').waitFor();};
 const saves=()=>page.evaluate(()=>calls.filter(call=>call.action==='saveProfile').length);
 const noMessaging=async()=>assert.deepEqual(await page.evaluate(()=>calls.filter(call=>['generate','quick','approve','sendNow','attentionAction'].includes(call.action))),[]);
 const save=async()=>{await page.locator('[data-action=save-relationship]').click();await page.waitForFunction(()=>!busy);};
 await page.goto(url);await open(1);await setup();
 phase='older profiles default to Light, with accessible slider and bounded notes';
 assert.equal(await slider().inputValue(),'0');assert.equal(await slider().getAttribute('min'),'0');assert.equal(await slider().getAttribute('max'),'4');assert.equal(await slider().getAttribute('step'),'1');assert.equal(await slider().getAttribute('aria-valuetext'),'Light · PG-13');assert.equal(await page.getByRole('slider',{name:'Humor',exact:true}).count(),1);assert.equal(await page.locator('#person-humor-value').getAttribute('aria-live'),'polite');assert.equal(await notes().getAttribute('maxlength'),'2000');assert.equal(await notes().inputValue(),'');assert.match(await page.locator('#person-humor-help').textContent(),/Used only for this person/);assert.equal(await saves(),0);
 phase='responsive slider keeps its DOM identity, focus and position at every level';
 for(const width of [412,320]){
  await page.setViewportSize({width,height:915});await slider().scrollIntoViewIfNeeded();await slider().focus();await slider().press('Home');
  await page.evaluate(()=>{window.humorSlider=document.querySelector('#person-humor-level');window.panelScroll=document.querySelector('.relationship-body').scrollTop;});const bounds=await slider().boundingBox();
  for(const label of ['Playful','Sarcastic','Edgy','Extreme']){await slider().press('ArrowRight');assert.equal(await slider().getAttribute('aria-valuetext'),label);assert.equal(await page.locator('#person-humor-value').textContent(),label);assert(await page.evaluate(()=>document.querySelector('#person-humor-level')===humorSlider&&document.activeElement===humorSlider));const next=await slider().boundingBox();assert(Math.abs(next.x-bounds.x)<1&&Math.abs(next.y-bounds.y)<1&&Math.abs(next.width-bounds.width)<1,JSON.stringify({bounds,next}));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await page.locator('.person-humor').screenshot({path:`dist/person-humor-${width}.png`});
 }
 assert.match(await page.locator('#person-humor-description').textContent(),/Raunchy adult innuendo and strong language when welcome/);assert.match(await page.locator('#person-humor-description').textContent(),/non-graphic/);assert.equal(await saves(),0);
 phase='notes, live refresh and escaped content preserve edits and caret';
 const example='We say “five-star chef” after burning toast. Keep it affectionate.';await notes().fill(example);await notes().focus();await page.evaluate(()=>{window.jokeNotes=document.querySelector('#person-inside-jokes');jokeNotes.setSelectionRange(8,8);});
 await page.evaluate(async()=>{chats[1].relationship={...chats[1].relationship,humorLevel:2,insideJokes:'An older saved example',revision:2};await onMessagesChanged();});
 assert.equal(await slider().inputValue(),'4');assert.equal(await notes().inputValue(),example);assert(await page.evaluate(()=>document.querySelector('#person-inside-jokes')===jokeNotes&&document.activeElement===jokeNotes&&jokeNotes.selectionStart===8));assert.equal(await page.locator('#relationship-context').inputValue(),'Existing relationship notes');assert.equal(await page.locator('#draft').inputValue(),'Existing manual draft');
 const escaped='</textarea><img src=x onerror="window.injected=1"> A nickname & why it is funny';await notes().fill(escaped);await close();await setup();assert.equal(await notes().inputValue(),escaped);assert.equal(await page.locator('.person-humor img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);
 await notes().fill('x'.repeat(2001));assert.equal((await notes().inputValue()).length,2000);assert.equal(await page.locator('#inside-jokes-count').textContent(),'2000/2000');await notes().fill(example);
 phase='save level four preserves consent, mode, tone, notes and recipient';
 await save();const high=await page.evaluate(()=>calls.filter(call=>call.action==='saveProfile').at(-1).p);assert.equal(high.humorLevel,4);assert.equal(high.insideJokes,example);
 for(const [key,value] of Object.entries({thread:1,cloudEnabled:true,autoDraft:true,autoSend:true,autoDelay:900,engagement:'always_reply',relationshipKind:'Friend',tone:'Myself (beta)',shareLocation:false,body:'Existing relationship notes'}))assert.equal(high[key],value,key);
 assert(await page.locator('[data-action=save-relationship]').isDisabled());await close();await page.locator('[data-action=back]').click();await open(2);await setup();assert.equal(await slider().inputValue(),'0');assert.equal(await notes().inputValue(),'');assert(await page.locator('[name=person-mode][value=off]').isChecked());
 await notes().fill('Our little catchphrase');await save();const low=await page.evaluate(()=>calls.filter(call=>call.action==='saveProfile').at(-1).p);assert.equal(low.humorLevel,0);assert.equal(low.insideJokes,'Our little catchphrase');assert.equal(low.thread,2);assert.equal(low.cloudEnabled,false);assert.equal(low.autoDraft,false);assert.equal(low.autoSend,false);assert.equal(low.engagement,'natural');assert.equal(await page.evaluate(()=>chats[1].relationship.humorLevel),4);
 phase='failed saves keep unsaved values, and navigating does not transfer them';
 await slider().focus();await slider().press('End');await notes().fill('Unsaved joke for person two');await page.evaluate(()=>{failSave=true;});await save();assert.match(await page.locator('#toast').textContent(),/could not be saved/);assert.equal(await slider().inputValue(),'4');assert.equal(await notes().inputValue(),'Unsaved joke for person two');assert(await page.locator('[data-action=save-relationship]').isEnabled());assert.equal(await page.evaluate(()=>chats[2].relationship.humorLevel),0);
 await close();await page.locator('[data-action=back]').click();await open(1);await setup();assert.equal(await slider().inputValue(),'4');assert.equal(await notes().inputValue(),example);
 phase='an in-flight save applies only to its original contact';
 await slider().focus();await slider().press('Home');await notes().fill('Saved later for person one');await page.evaluate(()=>{failSave=false;holdSave=true;});await page.locator('[data-action=save-relationship]').click();await page.waitForFunction(()=>saveReplies.length===1);
 await page.evaluate(()=>openIntent({thread:2}));await page.evaluate(()=>{holdSave=false;saveReplies.shift()();});await page.waitForFunction(()=>!busy);assert.equal(await page.locator('.chat-person h2').textContent(),'Other person');
 if(!await page.locator('#person-humor-level').count())await setup();assert.equal(await slider().inputValue(),'4');assert.equal(await notes().inputValue(),'Unsaved joke for person two');assert.equal(await page.evaluate(()=>chats[1].relationship.humorLevel),0);assert.equal(await page.evaluate(()=>chats[2].relationship.insideJokes),'Our little catchphrase');await noMessaging();assert.deepEqual(errors,[]);
 phase='demo persistence and validation use the same flat profile fields';
 const demo=await browser.newPage({viewport:{width:412,height:915}});await demo.goto(url);await demo.locator('#draft').waitFor();
 await demo.evaluate(async()=>{const p={thread:1,body:'Demo context',samples:'',cloudEnabled:false,autoDraft:false,autoSend:false,autoDelay:300,engagement:'natural',humorLevel:4,insideJokes:'Demo catchphrase'};await demoApi('saveProfile',p);window.invalidHumor=[];for(const invalid of [{humorLevel:5},{humorLevel:1.5},{insideJokes:'x'.repeat(2001)}]){try{await demoApi('saveProfile',{...p,...invalid});invalidHumor.push(false);}catch{invalidHumor.push(true);}}});assert.deepEqual(await demo.evaluate(()=>invalidHumor),[true,true,true]);await demo.reload();await demo.locator('#draft').waitFor();await demo.locator('[data-action=toggle-profile]').click();assert.equal(await demo.locator('#person-humor-level').inputValue(),'4');assert.equal(await demo.locator('#person-inside-jokes').inputValue(),'Demo catchphrase');await demo.close();
 console.log('PASS: humor defaults, accessible five-step responsive slider, 2000-character escaped notes, live focus/unsaved preservation, level0/4 payloads, mode/consent preservation, contact isolation, failed and delayed saves,320px layout, and demo persistence/validation. Fictional bridge only; no messages or AI.');
 }catch(error){throw new Error(`${phase}: ${error.message}`,{cause:error});}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1);});
