const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true});
 const p=await b.newPage({viewport:{width:412,height:915}});let exceptions=[];p.on('pageerror',e=>exceptions.push(e.message));
 await p.goto('http://127.0.0.1:8769');await p.locator('#draft').waitFor();
 await p.screenshot({path:'dist/phone-preview.png',fullPage:true});
 const before=await p.evaluate(async()=>(await demoApi('snapshot')).jobs.length);
 await p.getByRole('button',{name:'Schedule send',exact:true}).click();
 p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'5 min',exact:true}).click();
 await p.waitForFunction(()=>!document.querySelector('#draft').disabled);
 assert.equal(await p.evaluate(async()=>(await demoApi('snapshot')).jobs.length),before);
 await p.locator('#draft').fill('<img src=x onerror="window.injected=true">');
 await p.getByRole('button',{name:'Schedule send',exact:true}).click();
 assert.equal(await p.evaluate(()=>window.injected),undefined);
 p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'30 min',exact:true}).click();
 await p.locator('.scheduled-banner').waitFor();
 await p.getByRole('button',{name:'Back to conversations'}).click();
 await p.getByRole('button',{name:'Queue',exact:true}).click();
 await p.locator('.queue-card').waitFor();assert.equal(await p.locator('.queue-card img').count(),0);
 await p.getByRole('button',{name:'Cancel send'}).click();
 await p.waitForFunction(()=>document.querySelector('.status-label').textContent.trim()==='cancelled');
 await p.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Messages',exact:true}).click();
 await p.locator('.row').filter({hasText:'Maya Chen'}).click();
 await p.getByRole('button',{name:'Schedule send',exact:true}).click();
 await p.getByRole('button',{name:'Custom',exact:true}).click();await p.locator('#custom-delay').fill('10081');
 await p.getByRole('button',{name:'Set timer',exact:true}).click();
 assert((await p.locator('#toast').textContent()).includes('1 to 10,080'));
 assert.equal(await p.evaluate(async()=>(await demoApi('snapshot')).jobs.filter(j=>j.status==='scheduled').length),0);
 assert.deepEqual(exceptions,[]);console.log('PASS: rejected approval, escaped text, custom delay bounds, clean initial phone screenshot.');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
