const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let page,phase='launch';try{
 page=await browser.newPage({viewport:{width:412,height:915}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{
  const clone=v=>JSON.parse(JSON.stringify(v)),interval=window.setInterval;window.setInterval=(fn,ms,...args)=>ms===3500?0:interval(fn,ms,...args);
  window.calls=[];window.incoming={id:'first-share',text:'Look at this https://example.com/?a=1&b=2 <script>no()</script>',attachmentCount:0,status:'pending',canImport:true};window.heldImports=[];window.holdImport=false;window.importFailure='';window.loseAck=false;
  window.rows=[{thread_id:1,_id:11,address:'+12025550101',name:'Maya Chen',body:'What do you think?',date:Date.now(),type:1,read:1},{thread_id:2,_id:22,address:'+12025550102',name:'Jordan Ellis',body:'Hey there',date:Date.now()-1000,type:1,read:1}];
  window.savedDrafts={1:'My existing thought',2:''};window.staged={};
  window.fixture={inbox:rows,defaultSms:true,permissions:true,contactsAllowed:true,notifications:true,exact:true,sims:[{id:1,name:'Test SIM'}],sub:1,jobs:[],cloud:{configured:true},inAppSuggestions:true,autoDraft:false,theme:'midnight',inboxComplete:true};
  const access=()=>({readSms:fixture.permissions,defaultSms:fixture.defaultSms,contacts:fixture.contactsAllowed});
  const files=thread=>({items:staged[thread]||[],enabled:true,maxItems:6});
  window.share=(id,text,count=0,extra={})=>{incoming={id,text,attachmentCount:count,status:'pending',canImport:true,...extra};onShareReceived();};
  window.Native={call(id,action,raw){const p=JSON.parse(raw);calls.push({action,p});const finish=()=>{let result={},error=null;const row=rows.find(r=>r.thread_id===p.thread)||rows[0];
   if(action==='snapshot')result=fixture;
   else if(action==='smsRoleStatus')result={defaultSms:fixture.defaultSms,permissions:fixture.permissions,pending:false};
   else if(action==='shareState')result=incoming||{};
   else if(action==='cancelShare'){if(incoming?.id===p.id)incoming=null;}
   else if(action==='launchInbox'||action==='cacheInbox')result={inbox:rows,hasMore:false,snapshot:'test',cacheOnly:true,readOnly:true,access:access()};
   else if(action==='launchHistories'||action==='prefetchHistory')result={conversations:[],access:access()};
   else if(action==='cacheHistory')result={thread:p.thread,address:row.address,name:row.name,history:[row],hasMore:false,snapshot:'test',cacheOnly:true,readOnly:true,access:access()};
   else if(action==='contacts')result={allowed:fixture.contactsAllowed,contacts:rows.filter(r=>(r.name+r.address).toLowerCase().includes((p.query||'').toLowerCase())).map(r=>({name:r.name,number:r.address,label:'Mobile'}))};
   else if(action==='compose'){const r=rows.find(r=>r.address===p.address);if(!r)error='Choose a test contact.';else result={thread:r.thread_id,address:r.address,name:r.name};}
   else if(action==='conversation')result={thread:p.thread,address:row.address,name:row.name,base:row._id,history:[row],hasMore:false,relationship:{cloudEnabled:true,autoDraft:false,tone:'Natural'},draft:savedDrafts[p.thread]?{body:savedDrafts[p.thread],engine:'Edited by you',base:row._id}:null,attachments:files(p.thread),readOnly:false};
   else if(action==='replyProfile')result={thread:p.thread,address:row.address,name:row.name,relationship:{cloudEnabled:true,autoDraft:false,tone:'Natural'},profileRevision:1,access:access()};
   else if(action==='saveDraft')savedDrafts[p.thread]=p.body;
   else if(action==='importShare'){
    if(importFailure){error=importFailure;importFailure='';incoming={...incoming,status:'error',canImport:true,error};}
    else if(incoming?.id===p.id&&incoming.status==='imported')result={id:p.id,thread:p.thread,address:row.address,alreadyImported:true};
    else if(!fixture.permissions||!fixture.defaultSms)error='Choose Reply Pilot as your default app first.';
    else if(!incoming||p.id!==incoming.id)error='This share has changed.';
    else if(p.expectedAddress!==row.address||p.expectedBase!==row._id||p.expectedDraftBody!==(savedDrafts[p.thread]||''))error='The draft changed. Review it and try again.';
    else{const body=[savedDrafts[p.thread],incoming.text].filter(Boolean).join('\n\n');if(body.length>1600)error='Share up to 1,600 characters at a time.';else{savedDrafts[p.thread]=body;staged[p.thread]=[...(staged[p.thread]||[]),...Array.from({length:incoming.attachmentCount},(_,i)=>({id:p.id+'-'+i,name:'Shared photo '+(i+1)+'.jpg',mime:'image/jpeg',bytes:42000}))];result={id:p.id,thread:p.thread,address:row.address,base:row._id,text:body,attachments:files(p.thread)};incoming={...incoming,status:'imported',result};}}
   }
   else if(['generate','suggestReply','sendNow','sendMms','approve'].includes(action))error='Unexpected AI or send request.';
   if(action==='importShare'&&result.id&&loseAck){loseAck=false;error='Return to Reply Pilot to review this share.';result={};}
   nativeResult(id,clone(result),error);
  };if(action==='importShare'&&holdImport)heldImports.push(finish);else setTimeout(finish,0);}};
 });
 const count=action=>page.evaluate(a=>calls.filter(c=>c.action===a).length,action);
 await page.goto(process.env.REPLY_PILOT_URL||'http://127.0.0.1:18769');await page.getByRole('heading',{name:'Share with…'}).waitFor();await page.locator('[data-action=share-recent][data-thread="1"]').waitFor();
 phase='cold share recipient picker, escaped text, no native import';assert.match(await page.locator('.share-preview').innerText(),/<script>no\(\)<\/script>/);assert.equal(await page.locator('.share-preview script').count(),0);assert.equal(await count('importShare'),0);
 await page.locator('[data-action=share-recent][data-thread="1"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);assert.equal(await page.locator('#draft').inputValue(),'My existing thought');assert(await page.locator('#accept').isDisabled());assert(await page.locator('[data-action=generate]').isDisabled());assert.equal(await count('importShare'),0);
 await page.locator('#draft').fill('My edited thought');assert(await page.locator('#accept').isDisabled());await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>!document.querySelector('#share-review'));assert.equal(await page.locator('#draft').inputValue(),'My edited thought\n\nLook at this https://example.com/?a=1&b=2 <script>no()</script>');assert.equal(await count('importShare'),1);assert.equal(await page.evaluate(()=>calls.find(c=>c.action==='importShare').p.expectedDraftBody),'My edited thought');
 phase='resume does not replay an imported share';await page.evaluate(()=>onNativeResume());assert.equal(await page.locator('#share-review').count(),0);assert.equal(await count('importShare'),1);assert.equal(await page.locator('#draft').inputValue(),await page.evaluate(()=>savedDrafts[1]));
 phase='warm image plus caption, change recipient, blocked controls while importing';await page.evaluate(()=>share('photo-share','A couple of photos',2));await page.getByRole('heading',{name:'Share with…'}).waitFor();await page.locator('[data-action=share-recent][data-thread="1"]').click();await page.locator('[data-action=share-choose]').click();await page.locator('#recipient').fill('+12025550102');await page.locator('[data-action=compose]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);await page.evaluate(()=>{holdImport=true;});await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>heldImports.length===1);assert(await page.locator('#draft').isDisabled());assert(await page.locator('#accept').isDisabled());assert.equal(await page.locator('[data-action=share-cancel]').isDisabled(),false);await page.evaluate(()=>{holdImport=false;heldImports.splice(0).forEach(f=>f());});await page.waitForFunction(()=>!document.querySelector('#share-review'));assert.equal(await page.locator('#draft').inputValue(),'A couple of photos');assert.equal(await page.evaluate(()=>staged[2].length),2);assert.equal(await count('importShare'),2);await page.screenshot({path:'dist/share-draft-0.9.12.png'});
 phase='attachment only and retry preserves draft, no duplicate import';await page.evaluate(()=>share('retry-share','',1));await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);await page.evaluate(()=>{importFailure='Attachment access expired. Share it again.';});await page.locator('[data-action=share-add]').click();await page.locator('#share-review .share-error').waitFor();assert.equal(await page.locator('#draft').inputValue(),'A couple of photos');assert.equal(await page.evaluate(()=>staged[2].length),2);await page.evaluate(()=>onNativeResume());assert.equal(await page.locator('[data-action=share-add]').isDisabled(),false);await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>!document.querySelector('#share-review'));assert.equal(await page.evaluate(()=>staged[2].length),3);assert.equal(await page.locator('#draft').inputValue(),'A couple of photos');
 phase='cancel leaves existing text and attachments';await page.evaluate(()=>share('cancel-share','Do not add this'));await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.locator('[data-action=share-cancel]').click();assert.equal(await page.locator('#draft').inputValue(),'A couple of photos');assert.equal(await page.evaluate(()=>staged[2].length),3);await page.evaluate(()=>onShareReceived());assert.equal(await page.locator('#share-review').count(),0);
 phase='new share replaces an in-flight offer without crossing recipients';await page.evaluate(()=>share('old-share','Old item'));await page.locator('[data-action=share-recent][data-thread="1"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);await page.evaluate(()=>{holdImport=true;});await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>heldImports.length===1);await page.evaluate(()=>share('replacement-share','New item'));await page.getByRole('heading',{name:'Share with…'}).waitFor();await page.evaluate(()=>{holdImport=false;heldImports.splice(0).forEach(f=>f());});assert.equal(await page.locator('.share-preview').innerText(),'New item');await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);assert.equal(await page.locator('#draft').inputValue(),'A couple of photos');await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>!document.querySelector('#share-review'));assert.equal(await page.locator('#draft').inputValue(),'A couple of photos\n\nNew item');
 phase='cancel a slow external provider immediately without blocking chat';await page.evaluate(()=>share('slow-share','Should not be added',1));await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);const kept=await page.locator('#draft').inputValue();await page.evaluate(()=>{holdImport=true;});await page.locator('[data-action=share-add]').click();await page.waitForFunction(()=>heldImports.length===1);await page.locator('[data-action=share-cancel]').click();assert.equal(await page.locator('#share-review').count(),0);assert.equal(await page.locator('#draft').isDisabled(),false);await page.waitForFunction(()=>incoming===null);await page.evaluate(()=>{holdImport=false;heldImports.splice(0).forEach(f=>f());});assert.equal(await page.locator('#draft').inputValue(),kept);assert.equal(await page.evaluate(()=>staged[2].length),3);
 phase='invalid external share cannot import, compact layout';await page.evaluate(()=>share('invalid-share','',1,{status:'error',canImport:false,error:'This file type is not supported.'}));await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.locator('#share-review').waitFor();assert(await page.locator('[data-action=share-add]').isDisabled());await page.setViewportSize({width:320,height:720});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'dist/share-review-320-0.9.12.png'});await page.locator('[data-action=share-cancel]').click();
 phase='committed share with lost acknowledgment reconciles fresh draft, preserves newer edits';
 for(const mode of ['resume-untouched','resume-edited','retry-edited']){
  const before=await page.evaluate(()=>savedDrafts[2]);await page.evaluate(id=>share(id,'Lost acknowledgment text'),mode);await page.locator('[data-action=share-recent][data-thread="2"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);await page.evaluate(()=>{loseAck=true;});await page.locator('[data-action=share-add]').click();await page.locator('#share-review .share-error').waitFor();
  if(mode.endsWith('edited'))await page.locator('#draft').fill('My newer owner edit '+mode);
  if(mode==='retry-edited')await page.locator('[data-action=share-add]').click();else await page.evaluate(()=>onNativeResume());
  await page.waitForFunction(()=>!document.querySelector('#share-review')&&!document.querySelector('#chat-hydration'));assert.equal(await page.locator('#draft').inputValue(),mode.endsWith('edited')?'My newer owner edit '+mode:before+'\n\nLost acknowledgment text');
 }
 phase='permission loss closes private chat, no AI or send';await page.evaluate(()=>share('permission-share','Test'));await page.locator('[data-action=share-recent][data-thread="1"]').click();await page.waitForFunction(()=>document.querySelector('[data-action=share-add]')?.disabled===false);await page.evaluate(()=>{fixture.permissions=false;onMessageAccessChanged({defaultSms:true,readSms:false,contacts:true});});assert.equal(await page.locator('#share-review').count(),0);
 const dangerous=await page.evaluate(()=>calls.filter(c=>['generate','suggestReply','sendNow','sendMms','approve','analyzeMedia'].includes(c.action)));assert.deepEqual(dangerous,[]);assert.deepEqual(errors,[]);
 console.log('PASS: cold/warm share picker, escaped text/link, explicit review, owner draft append, images/caption, attachment-only, retry/cancel, resume dedupe, recipient change, replacement race, invalid files, permission loss and compact layout; no real SMS, attachments or AI used.');
 }catch(error){if(page){await page.screenshot({path:'dist/share-failure.png'});console.log(await page.evaluate(()=>({calls:calls.slice(-12),text:document.body.innerText.slice(-2500)})));}throw new Error(phase+': '+error.message,{cause:error});}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
