const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8769');
 await page.getByRole('textbox',{name:'Edit your reply'}).waitFor();
 await page.screenshot({path:'dist/desktop-preview.png',fullPage:true});
 assert.equal(await page.locator('#draft').inputValue(),'what time were you thinking?');
 await page.locator('#reply-setup').click();
 await page.locator('[name=person-tone][value=Warm]').check();
 await page.getByRole('button',{name:'Save profile',exact:true}).click();
 await page.waitForFunction(async()=>(await demoApi('conversation',{thread:1})).relationship.tone==='Warm');
 await page.getByRole('button',{name:'Close reply setup',exact:true}).click();
 await page.getByRole('button',{name:'Redraft',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#draft').value.includes('catch up!'));
 await page.locator('#draft').fill('A manually edited reply.');
 await page.locator('#reply-setup').click();
 await page.locator('[name=person-tone][value="Use AI intuition"]').check();
 await page.getByRole('button',{name:'Save profile',exact:true}).click();
 await page.waitForFunction(async()=>(await demoApi('conversation',{thread:1})).relationship.tone==='Use AI intuition');
 assert.equal(await page.locator('#draft').inputValue(),'A manually edited reply.');
 assert(await page.locator('[name=person-tone][value="Use AI intuition"]').isChecked());
 await page.getByRole('button',{name:'Close reply setup',exact:true}).click();
 await page.getByRole('button',{name:'Schedule send',exact:true}).click();
 assert.equal(await page.locator('#draft').inputValue(),'A manually edited reply.');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'5 min',exact:true}).click();
 await page.locator('.scheduled-banner').waitFor();
 await page.getByRole('button',{name:'Queue',exact:true}).click();
 await page.getByRole('button',{name:'Cancel send'}).waitFor();
 assert(await page.locator('.queue-card').innerText().then(s=>s.includes('A manually edited reply.')));
 await page.getByRole('button',{name:'Cancel send'}).click();
 await page.waitForFunction(()=>document.querySelector('.status-label').textContent.trim()==='cancelled');
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.locator('#tone-setting').selectOption('Brief');
 await page.getByRole('button',{name:'Save preferences'}).click();
 assert.equal(await page.locator('#tone-setting').inputValue(),'Brief');
 await page.locator('#tone-setting').selectOption('Use AI intuition');
 await page.getByRole('button',{name:'Save preferences'}).click();
 assert.equal(await page.evaluate(async()=>(await demoApi('snapshot')).tone),'Use AI intuition');
 await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Messages',exact:true}).click();
 await page.setViewportSize({width:412,height:915});
 await page.screenshot({path:'dist/phone-preview.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'Back to conversations'}).click();
 await page.getByRole('textbox',{name:'Find a conversation'}).fill('Jordan');
 assert.equal(await page.locator('.row').count(),1);
 await page.getByRole('textbox',{name:'Find a conversation'}).fill('');
 await page.screenshot({path:'dist/inbox-preview.png',fullPage:true});
 await page.getByRole('button',{name:'Media',exact:true}).click();
 await page.getByRole('heading',{name:'No multimedia messages yet.'}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: editing, tone/redraft, scheduled acceptance, cancellation, saved preferences, search, empty media, mobile overflow, JavaScript runtime.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
